### ISSUE TITLE
SITL PX4 + Gazebo

### ISSUE THREAD

**Issue by dferruzzo** [dferruzzo/mavdsk-python#10]
Implementar a simulação SITL utilizando PX4+Gazebo, 

`make px4_sitl gz_x500`

Opções:
gz_x500: phony
gz_x500_aruco: phony
gz_x500_baylands: phony
gz_x500_depth: phony
gz_x500_depth_aruco: phony
gz_x500_depth_baylands: phony
gz_x500_depth_lawn: phony
gz_x500_depth_rover: phony
gz_x500_depth_windy: phony
gz_x500_lawn: phony
gz_x500_lidar: phony
gz_x500_lidar_aruco: phony
gz_x500_lidar_baylands: phony
gz_x500_lidar_lawn: phony
gz_x500_lidar_rover: phony
gz_x500_lidar_windy: phony
gz_x500_mono_cam: phony
gz_x500_mono_cam_aruco: phony
gz_x500_mono_cam_baylands: phony
gz_x500_mono_cam_down: phony
gz_x500_mono_cam_down_aruco: phony
gz_x500_mono_cam_down_baylands: phony
gz_x500_mono_cam_down_lawn: phony
gz_x500_mono_cam_down_rover: phony
gz_x500_mono_cam_down_windy: phony
gz_x500_mono_cam_lawn: phony
gz_x500_mono_cam_rover: phony
gz_x500_mono_cam_windy: phony
gz_x500_rover: phony
gz_x500_vision: phony
gz_x500_vision_aruco: phony
gz_x500_vision_baylands: phony
gz_x500_vision_lawn: phony
gz_x500_vision_rover: phony
gz_x500_vision_windy: phony
gz_x500_windy: phony

pelo seguinte:

- O modelo do veículo é melhor.
- Podemos ter acesso aos parâmetros do modelo para comparação.
- Podemos ajustar o cenário da simulação.

Estou utilizando;

- Gazebo Harmonic versão 8.6.0. https://gazebosim.org/docs/harmonic/install_ubuntu/
- Importante; https://discuss.px4.io/t/starting-gazebo-and-px4-separately/2531

# To-Do:

- [x] Configurar PX4 SITL para Gazebo.
- [x] Estudar como é implementado o veículo utilizado, é o X500.
- [x] Verificar os sinais de teste para que durante o teste garantir que  
       - a posição xyz do veículo possa ser conhecida.
       - a altura do veículo possa ser conhecida e controlada.
- [x] Criar um script para:
       - Definir o tipo de veículo.
       - Definir a posição e atitude inicial do veículo.
       - Definir o cenário da simulação.
       - Rodar a simulação.

**Comment by dferruzzo** [comment]
No inicio da simulação o ângulo de guinada está perto de 90 graus.
- [ ] Como configurar a atitude inicial?

**Comment by dferruzzo** [comment]
`PX4_SYS_AUTOSTART=4001` Airframe autostart id.
`PX4_GZ_MODEL_POSE="0,2,0,0,0,0"` Seleciona a pose inicial, `x,y,z,roll, pitch,yaw`.
`PX4_SIM_MODEL=gz_x500` Inicia gazebo e seleciona o modelo ´x500´.

`PX4_SYS_AUTOSTART=4001 PX4_GZ_MODEL_POSE="0,2,0,0,0,0" PX4_SIM_MODEL=gz_x500 ./build/px4_sitl_default/bin/px4`

**Comment by dferruzzo** [comment]
No final coloquei o set-point de atitude dentro do Offboard - Attitude command.
